name: "Task"
description: "Track a development or testing task"
labels: ["type:task"]
body:
  - type: input
    id: title
    attributes:
      label: "Task Title"
  - type: textarea
    id: description
    attributes:
      label: "Description"
  - type: input
    id: spec
    attributes:
      label: "Linked Spec (Issue #)"
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - P0
        - P1
        - P2
        - P3
